/*
  Description: Simulation of a PMT

  Author Anyes Taffard
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

const int dbg = 0;

#define      NDYNODES  6       //Number of PMT dynodes
const double EperEle = 20;     //20 Volts per electron
const double QE      = 0.23;   //Assume photon wavelength is 400 nm
                               //and corresponding Quantum Eff =23%
const int    NMC     = 10000;  //Number of test experiment
const int    NPHO    = 1;      //Number of photons stricking the photocathode

/*
  Use Marsaglia's RNG 
*/
unsigned long long int v;
//_______________________________________________
unsigned long long int64() {
  v ^= v >> 21; v ^= v << 35; v ^= v >> 4;
  return v*2685821657736338717LL;
}
//_______________________________________________
void setSeed(unsigned long long int j) {
  v = 4101842887655102017LL;
  v ^= j;
  v = int64();
}
//_______________________________________________
double myRandom() {
  return 5.42101086242752217e-20*int64();
}

//_______________________________________________
// Generate random poisson number. Park's version 
unsigned long randPoisson(double mu);

//_______________________________________________
// Generate exponentially distributed positive number
long double randExponential(double mu);

//_______________________________________________
// Simulate the number of photoelectrons generated by one photon
long double photoElectrons(int nPhotons);

//_______________________________________________
// Compute number of electron release
// when one electron hit dynode
long double meanDynodeElectrons(long double E);

//_______________________________________________
// Simulate the number of dynode electrons produced
long double dynodeElectrons(long double nIncomingEle, long double E);

//_______________________________________________
// Simulate a sequence of dynodes. V[] is the dynode voltages
long double photonToElectrons(int nPhotons, double V[], int nDynodes);


//_________________________________________
//_________________________________________
int main()
{
  //Voltage of the dynode V0<V1<Vhv etc...
  double VDynode[NDYNODES]={150, 300, 450, 600, 750, 850};

  //Set random seed
  setSeed( time(NULL) * 391740128);
    
  //Open output file
  FILE* fPtr;
  char fileName[] = "pmt_photoEle.dat";
  fPtr = fopen(fileName,"w"); 
  if( fPtr == NULL ){
    printf("Cannot open file %s. Exitting\n",fileName);
    exit(1);
  }
  printf("Opened file %s \n",fileName);

  clock_t t = clock(); //Grab time
  for(int iTest=0; iTest<NMC; iTest++){
    long double nEle = photonToElectrons(NPHO,VDynode,NDYNODES);
    if(nEle>0) fprintf(fPtr,"%.4Lf \n",nEle);
  }

  t = clock() - t; //get time difference
  float sec = ((float) t)/CLOCKS_PER_SEC;
  printf("\nExecution times %d clicks (%f seconds) for an experiment with %i photon \n",(int) t, sec, NPHO);
    
  //To check the Poisson number generator
  /*
  double myMu = 2;
  for(int i=0; i<10000; i++)
    fprintf(fPtr,"%li \n",randPoisson(myMu));
  */
 
  fclose(fPtr);
  
  return 0;
}


//_______________________________________________
long double photoElectrons(int nPhotons)
{
  double pe =0;
  for(int i=0; i< nPhotons; i++){
    if( myRandom() < QE) pe++;
  }
  return pe;
}
//_______________________________________________
long double meanDynodeElectrons(long double E)
{
  if(E<0) return 0;
  return E/EperEle;
}

//_______________________________________________
long double dynodeElectrons(long double nIncomingEle, long double E)
{
  double mean = nIncomingEle * meanDynodeElectrons(E);
  double nEle = randPoisson(mean);
  if(dbg==1) printf("\t\tDynodeElectrons %f nEle %f \n",mean,nEle);
  return nEle;
}

//_______________________________________________
long double photonToElectrons(int nPhotons, double V[], int nDynodes)
{
  double nEle = photoElectrons(nPhotons);
  double lastVoltage = 0;
  if(dbg==1) printf("nPhotons %i nEle %4.1f\n",nPhotons, nEle); 
 
  for(int iDynode=0; iDynode<nDynodes; iDynode++){
    double voltDrop = V[iDynode] -  lastVoltage;
    nEle += dynodeElectrons(nEle, voltDrop);
    if(dbg==1) printf("\tDynode: %i \t nEle %4.1f Vdrop %f lastV %f \n",
		      iDynode, nEle, voltDrop, lastVoltage);
    lastVoltage = V[iDynode];
  }
  return nEle;
}

//_______________________________________________
//Park's algorthim
unsigned long randPoisson(double mu)
{
  unsigned long n=0;
  long double x = 0;
  while (x<mu){
    x += randExponential(1.0);
    n++;
  }
  if(dbg==1) printf("\t\tRandPoisson n %lu x %Le\n",n-1, x);
  return (n>0) ? n-1 : 0;
}

//_______________________________________________
// Generate exponentially distributed positive number
long double randExponential(double mu)
{
  long double expRand = -mu * log(1.0 - myRandom());
  //  printf("randExp %Lf \n",expRand);
  return expRand;
}
